name: Node.js CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   ci:
    name: Deployment
    uses: amauriciolab/dummy-app/.github/workflows/gha.workflows.build-node.yml@main


 
